# Site settings
title: Jihyun Park
description: Jihyun Park's website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jihyun Park
user_description: I am a MS student majoring in the Department of Computer Science at Seoul National University. I have received BS in Korea University. Over the course of undergraduate school, I interned at NAVER. My research interests are Data Analysis, Social Network Analysis, Anomaly Detection, and specifically focusing on Review Spam Detection.    
user_title: Software Developer
email: jihyun.park@snu.ac.kr
twitter_username:
github_username:  jihyun300
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
